openapi: 3.1.1
info:
  title: portfolio shop
  description: An API that is used to manage a shop, create user accounts and handle transactions.
  version: 1.0.0

tags:
  - name: utility
    description: other requests that handles sessions or info
  - name: products
    description: requests regarding the shop's products
  - name: users
    description: requests regarding the users
  - name: userAuth
    description: requests regarding a specific user's authentication methods  (AUTHENTICATION REQUIRED)
  - name: cart
    description: requests regarding an user's shopping cart, automatically created if it doesn't exist (AUTHENTICATION REQUIRED)
  - name: orders
    description: requests regarding each user's transactions (AUTHENTICATION REQUIRED)
servers:
  - url: http://localhost:8000/v1

paths:
  /login:
    post:
      security:
        - googleOAuth: [profile, email]
        - facebookOAuth: [profile, email]
      tags:
        - utility
  /docs:
    get:
      description: displays this YAML file via the swagger-ui library
      tags:
        - utility
  /products:
    get:
      tags:
        - products
      summary: List all products in the shop
      operationId: getProducts
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: server error
  /products/{product_id}:
    get:
      tags:
        - products
      summary: get a single shop product by providing an id
      operationId: getProductById
      parameters:
        - name: product_id
          in: path
          required: true
      responses:
        "200":
          description: the requested product
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Product"
        "404":
          description: product not found
  /users:
    get:
      tags:
        - users
      summary: get all users from the database, without sensitive data
      operationId: getUsers
      responses:
        "200":
          description: All users in the database, ordered from most to least recently created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "500":
          description: server error
    post:
      tags:
        - users
      summary: Create a new user, once a proper authentication method was provided.
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUserInput"
      responses:
        "201":
          description: the created user, without the authentication data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /users/{user_id}:
    get:
      tags:
        - users
      summary: get a single user's info, without sensitive data
      operationId: getUserById
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: the requested user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: user not found
        "500":
          description: server error
    put:
      security:
        - googleOAuth: []
        - facebookOAuth: []
      tags:
        - users
      summary: updates the user
      operationId: updateUser
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserProfileInput"
      responses:
        "200":
          description: the updated user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: user not found
        "500":
          description: server error
    delete:
      security:
        - googleOAuth: []
        - facebookOAuth: []
      tags:
        - users
      summary: deletes the user with the selected id
      operationId: deleteUser
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: user deleted successfully
        "404":
          description: user not found
        "500":
          description: server error
  /users/{user_id}/auth:
    get:
      security:
      - googleOAuth: []
      - facebookOAuth: []
      tags:
        - userAuth
      summary: fetches all auth methods available for that user
      operationId: getUserAuthList
      parameters:
        - name: user_id
      required: true
      responses:
        "200":
          description: all auth methods available for that user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAuth"
        "500":
          description: server error
    post:
      security:
      - googleOAuth: []
      - facebookOAuth: []
      tags:
        - userAuth
      summary: updates or creates a traditional username/password auth method
      operationId: updateOrCreateUserAuthPassword
      parameters:
        - name: user_id
      required: true
      responses:
        "200":
          description: all auth methods available for that user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAuth"
        "500":
          description: server error
  /users/{user_id}/auth/{provider}:
    get:
      security:
        - googleOAuth: []
        - facebookOAuth: []
      tags:
        - userAuth
      summary: requests a specific user authentication method
      operationId: getUserAuthByProvider
      parameters:
        - name: user_id
        - name: provider
      responses:
        "200":
          description: all auth methods available for that user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAuth"
        "404":
          description: user / userAuth not found
        "500":
          description: server error
    delete:
      security:
        - googleOAuth: []
        - facebookOAuth: []      
      tags:
        - userAuth
      summary: deletes the desired authentication  method
      operationId: deleteUserAuthByProvider
      parameters:
        - name: user_id
        - name: provider
      responses:
        "204":
          description: userAuth deleted successfully
        "404":
          description: user / userAuth not found
        "500":
          description: server error




  /users/{user_id}/cart:
    get:
      security:
      - googleOAuth: []
      - facebookOAuth: []
      tags:
        - cart
      summary: fetches the cart's infomations, without its actual items
      operationId: getCartByUserId
      parameters:
        - name: user_id
      required: true
      responses:
        "200":
          description: the cart's without the items 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "204":
          description: cart deleted
        "401":
          description: unauthorized without authentication
        "403":
          description: forbidden, the user_id doesn't match the current session's user_id
        "500":
          description: server error

    delete:
      security:
      - googleOAuth: []
      - facebookOAuth: []
      tags:
        - cart
      summary: delete the user's cart, all cart items are automatically deleted too
      operationId: deleteCart
      parameters:
        - name: user_id
      required: true
      responses:
        "204":
          description: cart deleted
        "401":
          description: unauthorized without authentication
        "403":
          description: forbidden, the user_id doesn't match the current session's user_id
        "500":
          description: server error

  /users/{user_id}/cart/checkout:
    post:
      security:
      - googleOAuth: []
      - facebookOAuth: []
      tags:
        - cart
      summary: a combination of many requests to create a new order with all items in the cart
      operationId: checkout
      parameters:
        - name: user_id
      required: true
      responses:
        "200":
          description: all auth methods available for that user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderWithItems"
        "401":
          description: unauthorized without authentication
        "403":
          description: forbidden, the user_id doesn't match the current session's user_id
        "500":
          description: server error
  

#TODO: finish this part and utility
  /users/{user_id}/cart/items:
    get:
      security:
        - googleOAuth: []
        - facebookOAuth: []
      tags:
        - cart
      summary: requests a specific user authentication method
      operationId: getUserAuthByProvider
      parameters:
        - name: user_id
        - name: provider
      responses:
        "200":
          description: all auth methods available for that user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAuth"
        "404":
          description: user / userAuth not found
        "500":
          description: server error
    delete:
      security:
        - googleOAuth: []
        - facebookOAuth: []      
      tags:
        - userAuth
      summary: deletes the desired authentication  method
      operationId: deleteUserAuthByProvider
      parameters:
        - name: user_id
        - name: provider
      responses:
        "204":
          description: userAuth deleted successfully
        "404":
          description: user / userAuth not found
        "500":
          description: server error





  /users/{user_id}/order/:
      get:
        security:
          - googleOAuth: []
          - facebookOAuth: []
        tags:
          - orders
        summary: fetches all orders made by the user
        operationId: getOrdersByUserId
        parameters:
          - name: user_id
        responses:
          "200":
            description: all orders made for that user, ordered by date (earliest to latest order)
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Order'
          "500":
            description: server error

  /users/{user_id}/order/{order_id}:
      get:
        security:
          - googleOAuth: []
          - facebookOAuth: []
        tags:
          - orders
        summary: fetches the order and the items that were bought
        operationId: getOrderByIds
        parameters:
          - name: user_id
          - name: order_id
        responses:
          "200":
            description: the order and order items
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/OrderWithItems"
          "404":
            description: user / order not found
          "500":
            description: server error
      put:
        security:
          - googleOAuth: []
          - facebookOAuth: []      
        tags:
          - orders
        summary: updates the status of the users order
        operationId: updateOrderStatus
        parameters:
          - name: user_id
          - name: order_id
        responses:
          "200":
            description: the contents of the Order
            contents:
              application/json:
                schema:
                  $ref: "#/components/schemas/Order"
          "404":
            description: user / order not found
          "500":
            description: server error


components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "tomato sauce"
        price:
          type: number
          example: 4.90
        description:
          type: string
          example: "A famous brand of tomato sauce"
          nullable: true
      required:
        - id
        - name
        - price
    ProductInput:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
        description:
          type: string
      required:
        - name
        - price
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: number
          example: "Johndoe123"
        fullname:
          type: string
          example: "John doe"
        email:
          type: string
          example: "jdoe123@gmail.com"
        created_at:
          type: string
          format: date
          example: "2026-05-17"
          pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
          default: "SQL NOW FUNCTION"
      required:
        - id
        - username
        - created_at
    UserAuth:
      type: object
      description: at least one of provider_id or password_hash must be present.
      properties:
        id:
          type: integer
        user_id:
          type: integer
        provider:
          type: string
        provider_id:
          type: string
          nullable: true
          description: must be present if password_hash isn't provided
        password_hash:
          type: string
          nullable: true
          description: must be present if provider_id isn't provided
      required:
        - id
        - user_id
        - provider
      anyOf:
        - required: [provider_id]
        - required: [password]

    NewUserAuthPassword:
      type: object
      properties:
        password: type_string
      required:
        - password

    NewUserInput:
      description: at least one of provider_id or password must be present.
      type: object
      properties:
        fullname:
          type: string
        username:
          type: string
        provider:
          type: string
          description: defaults to local if left empty
        provider_id:
          type: string
          description: must be present if password isn't provided
        password:
          type: string
          description: must be present if provider_id isn't provided
      required:
        - username
        - email
      anyOf:
        - required: [provider_id]
        - required: [password]

    UserProfileInput:
      description: designed to update username and fullname rows in the database
      type: object
      properties:
        username:
          type: string
          example: "JoDo31"
        fullname:
          type: string
          example: "John Doe"
      anyOf:
        - required: [username]
        - required: [fullname]


    Cart:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        delivery_address:
          type: string
          example: "Hell's kitchen"
        created_at:
          type: string
          format: date
          example: "2026-05-17"
          pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
          default: "SQL NOW FUNCTION"
        status:
          type: string
          example: "COMPLETED"
          description: one of these three values -> PENDING ; DELIVERY ; COMPLETED
        totalprice:
          type: number
          example: 20.95
          description: the sum of all ordered ites
        
    CartItem:
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        product_id:
          type: integer
          example: 1
        name:
          type: string
          example: "tomato sauce"
        price:
          type: number
          example: 4.90
        description:
          type: string
          example: "A famous brand of tomato sauce"
          nullable: true
        quantity:
          type: integer
          example: 4
        total_price:
          type: number
          example: 19.6

    CartItemInput:
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        product_id:
          type: integer
          example: 1
        quantity:
          type: integer
          example: 4   
      required:
        - user_id
        - product_id
        - quantity

    OrderWithItems:
      type: object
      properties:
        order:
          $ref: "#/components/schemas/Order"
        order_items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"

    Order:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        delivery_address:
          type: string
          example: "Hell's kitchen"
        created_at:
          type: string
          format: date
          example: "2026-05-17"
          pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
          default: "SQL NOW FUNCTION"
        status:
          type: string
          example: "COMPLETED"
          description: one of these three values -> PENDING ; DELIVERY ; COMPLETED
        totalprice:
          type: number
          example: 20.95
          description: the sum of all ordered ites

        
    OrderItem:
      type: object
      properties:
        order_id:
          type: integer
          example: 1
        name:
          type: string
          example: "tomato sauce"
        price:
          type: number
          example: 4.90
        description:
          type: string
          example: "A famous brand of tomato sauce"
          nullable: true
        quantity:
          type: integer
          example: 4


    OrderStatusInput:
      type: object
      properties:
        status:
          type: string
          example: PENDING
          description: one of these three values -> PENDING ; DELIVERY ; COMPLETED
      required:
        - status
       
  securitySchemes:
    googleOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            - profile
            - email
    facebookOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.facebook.com/v10.0/dialog/oauth
          tokenUrl: https://graph.facebook.com/v10.0/oauth/access_token
          scopes:
            - profile
            - email
